exports.el = {
    genderOptions: 'input[name=id_gender]',
    firstName: '#customer_firstname',
    lastName: '#customer_lastname',
    email: '#email',
    password: '#passwd',
    day: '#days',
    month: '#months',
    year: '#years',
    newsletter: '#newsletter',
    specialOffers: '#optin',
    addressFirstName: 'input[id=firstname]',
    addressLastName: 'input[id=lastname]',
    company: '#company',
    address1: '#address1',
    address2: '#address2',
    city: '#city',
    state: '#id_state',
    postalCode: '#postcode',
    addInfos: '#other',
    phone: '#phone',
    mobile: 'input[id$=mobile]',
    addressName: '#alias',
    submitAccount: '#submitAccount',
}